// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZQJQjv-TrVMvA_2u4JHX8LyYvUkbusg',
    appId: '1:150259610200:web:d5b090808fff878536902d',
    messagingSenderId: '150259610200',
    projectId: 'csen268-s25-g0',
    authDomain: 'csen268-s25-g0.firebaseapp.com',
    storageBucket: 'csen268-s25-g0.firebasestorage.app',
    measurementId: 'G-R53PC6BH24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYb6h5ITGg7h65Yv7TjtsdLRh2TyqyspQ',
    appId: '1:150259610200:android:b05995d2197f8c7d36902d',
    messagingSenderId: '150259610200',
    projectId: 'csen268-s25-g0',
    storageBucket: 'csen268-s25-g0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP58KA-mnxGbD4j0oF5gI5U8L0wqEisbI',
    appId: '1:150259610200:ios:f353c8fcceb783fd36902d',
    messagingSenderId: '150259610200',
    projectId: 'csen268-s25-g0',
    storageBucket: 'csen268-s25-g0.firebasestorage.app',
    iosBundleId: 'com.csen268.s25.g0',
  );
}
